# Site settings
title: Queen's World
email: patgalis@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Footer settings
footer:
  copyright: patrypatry
  location: Louisville, KY
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
  - title: dribbble
    url: https://dribbble.com/ppaattrry
  - title: behance
    url: https://www.behance.net/patriciagm
  - title: github
    url: http://github.com/patrypatry
  - title: linkedin
    url: http://linkedin.com/in/patrypatry


# Postal address (add as many lines as necessary)
address:
  - line: United States
  - line: Planet Earth

# Build settings
markdown: kramdown
permalink: pretty
